### ISSUE TITLE
package？

### ISSUE THREAD

**Issue by zdw-constantine** [chunxxc/lokatt#1]
Where is this package named "dist/lokattcu110-0.0.1-py3-none-any.whl" ?

**Comment by MaxLiu245** [comment]
> Where is this package named "dist/lokattcu110-0.0.1-py3-none-any.whl" ?

It seems that the author @chunxxc didn't release the package anywhere, pypi neither. Maybe installing from the source works (I haven't reproduced it yet :-)

**Comment by chunxxc** [comment]
Oops, my mistake that 'dist/' got on the gitignore list. I am sorry for the inconvenience and will try to fix it within a day.

**Comment by chunxxc** [comment]
Hi! I have just uploaded a new build of lokatt (wheel file and more efficient code). Although the wheel is available now, I recommend installing from source as you will need to compile the tensorflow\_io/dnaseq\_beam.so with your local CUDA anyway. I will keep this issue open for a while just in case. 
Feel free to let me know if you have problems reproducing the results in the paper!

**Comment by zdw-constantine** [comment]
Thank you for your help.
