### ISSUE TITLE
Trouble:

### ISSUE THREAD

**Issue by zdw-constantine** [chunxxc/lokatt#2]
Traceback (most recent call last):
  File "/home/XXX/.conda/envs/lokatt2/bin/lokatt", line 8, in <module>
    sys.exit(main())
  File "/home/XXX/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/__init__.py", line 38, in main
    args.func(args)
  File "/home/XXX/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/gpu_beamsearch_opt.py", line 205, in main
    output = dnaseq_beam(Px+1e-5, tf.Variable(batch_duration,dtype=tf.float32), tf.Variable(batch_tail,dtype=tf.float32),tf_trans,number_of_beams=PARAMS.beam)
  File "<string>", line 162, in dnaseq_beam
  File "/home/XXX/.conda/envs/lokatt2/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node DnaseqBeam}} = DnaseqBeam[number_of_beams=512]
All kernels registered for op DnaseqBeam:
  device='GPU'
 [Op:DnaseqBeam] name: 
2it [01:37, 48.93s/it]

Could you provide a more detailed configuration package? Thank you.

**Comment by chunxxc** [comment]
Hi! This bug is new to me. Could you provide all command lines you have run until this bug point? And specifically, what result did you get from compiling the .so file?

**Comment by zdw-constantine** [comment]
This program runs on a CPU device using the command "lokatt basecaller -fast5 Raw/ -output result/ -batch 60 -name test
", which is the environment I am currently configuring.
absl-py                      2.1.0
astunparse                   1.6.3
cachetools                   5.3.3
certifi                      2024.2.2
charset-normalizer           3.3.2
dm-tree                      0.1.8
flatbuffers                  24.3.25
gast                         0.4.0
google-auth                  2.29.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.63.0
h5py                         3.11.0
idna                         3.7
importlib_metadata           7.1.0
jax                          0.4.28
keras                        3.3.0
keras-nightly                2.5.0.dev2021032900
Keras-Preprocessing          1.1.2
libclang                     18.1.1
lokatt                       0.1.0
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
mdurl                        0.1.2
ml-dtypes                    0.3.2
namex                        0.0.8
numpy                        1.23.5
oauthlib                     3.2.2
opt-einsum                   3.3.0
optree                       0.11.0
packaging                    24.0
pip                          22.3.1
protobuf                     4.25.3
pyasn1                       0.6.0
pyasn1_modules               0.4.0
Pygments                     2.18.0
PyYAML                       6.0.1
requests                     2.31.0
requests-oauthlib            2.0.0
rich                         13.7.1
rsa                          4.9
scipy                        1.13.0
setuptools                   65.5.1
six                          1.15.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorboard-plugin-wit       1.8.1
tensorflow                   2.16.1
tensorflow-estimator         2.15.0
tensorflow-gpu               2.8.0
tensorflow-io-gcs-filesystem 0.37.0
termcolor                    1.1.0
tf-estimator-nightly         2.8.0.dev2021122109
tqdm                         4.66.4
typing_extensions            4.5.0
urllib3                      2.2.1
Werkzeug                     3.0.3
wheel                        0.38.4
wrapt                        1.12.1
zipp                         3.18.1

**Comment by chunxxc** [comment]
I'm sorry but Lokatt only runs on GPU as its core function is written with CUDA. And it would be super slow on a CPU as it has > 10 million parameters in the neural network.

**Comment by zdw-constantine** [comment]
Thank you for your answer ，but when run the code on GPU, the trouble list there:  
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/lokatt2/bin/lokatt", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/__init__.py", line 38, in main
    args.func(args)
  File "/home/xxx/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/gpu_beamsearch_opt.py", line 203, in main
    Px = myNN(batch_input)
  File "/home/xxx/.conda/envs/lokatt2/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/xxx/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/model_2RES2BI512_resoriginal.py", line 57, in call
    x = self.res1(x)
  File "/home/xxx/.conda/envs/lokatt2/lib/python3.9/site-packages/lokatt/model_2RES2BI512_resoriginal.py", line 87, in call
    hx = self.conv1(x)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling Conv1D.call().

{{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} No DNN in stream executor. [Op:Conv2D] name: 

Arguments received by Conv1D.call():
  • inputs=tf.Tensor(shape=(60, 4096, 1), dtype=float32)
2it [00:11,  5.67s/it]

**Comment by chunxxc** [comment]
Looks like a problem with the TensorFlow installation to me. In the list you give for the CPU there are two: tensorflow 2.16 and tensorflow-gpu 2.8. Could you check which tensorflow version you are running on the GPU? I would recommend removing the tensorflow-gpu 2.8 as it might not be compatible with most CUDA versions nowadays.
